In [21]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [117]:
dfs = pd.read_excel("MorphoLEX_en.xlsx", sheet_name=None)

dfs.pop('Presentation')
dfs.pop('All prefixes')
dfs.pop('All suffixes')
dfs.pop('All roots')

for key in dfs:
    dfs[key] = dfs[key][["MorphoLexSegm", "PRS_signature", "Word"]]

dfs = list(dfs.values())

In [118]:
morphemes = pd.concat(dfs).dropna().reset_index()
morphemes.pop("index")
morphemes["Word"] = morphemes["Word"].str.lower()

morphemes

      MorphoLexSegm PRS_signature      Word
0           {(alf)}         0,1,0       alf
1          {(alfa)}         0,1,0      alfa
2      {(alfresco)}         0,1,0  alfresco
3       {(algebra)}         0,1,0  algebras
4         {(alger)}         0,1,0     alger
...             ...           ...       ...
68618       {d'art}         0,0,0     d'art
68619      {d'etat}         0,0,0    d'etat
68620       {won't}         0,0,0     won't
68621       {let's}         0,0,0     let's
68622       {ain't}         0,0,0     ain't

[68623 rows x 3 columns]

In [119]:
deleted_char = [",", ".", ";", "/", "!", "?", "(", ")", "\n", "-", ":"]

def split_sentence(sentence:str):
    sentence = sentence.lower()
    for c in deleted_char:
        sentence = sentence.replace(c, " ")
    split = sentence.split(" ")
    split = [v for v in split if v not in ["", " "]]
    return split

def get_morphemes(sentence:str):
    split = split_sentence(sentence)
    print(f"Sentence length: {len(split)} words")
    morph = []

    errors = []

    for w in split:
        res = morphemes.loc[morphemes["Word"]==w]
        if(len(res)!=0):
            morph.append(res.index[0])
        elif(len(w.split("'"))>1 and len(morphemes.loc[morphemes["Word"]==w.split("'")[0]])>0):
            morph.append(w.split("'")[0])
        else:
            errors.append(w)

    print(f"> {len(morph)} recognized words: {errors}")

    return morph

In [126]:
morphemes.loc[morphemes["Word"]=="me"]

# Mots usuels manquants
# true, false

      MorphoLexSegm PRS_signature Word
20845        {(me)}         0,1,0   me

In [111]:
get_morphemes("""
Two households, both alike in dignity,
In fair Verona, where we lay our scene,
From ancient grudge break to new mutiny,
Where civil blood makes civil hands unclean.
From forth the fatal loins of these two foes
A pair of star-cross'd lovers take their life;
Whose misadventured piteous overthrows
Do with their death bury their parents' strife.
The fearful passage of their death-mark'd love,
And the continuance of their parents' rage,
Which, but their children's end, nought could remove,
Is now the two hours' traffic of our stage;
The which if you with patient ears attend,
What here shall miss, our toil shall strive to mend.
Both by myself and many other friends:
But he, his own affections' counsellor,
Is to himself--I will not say how true--
But to himself so secret and so close,
So far from sounding and discovery,
As is the bud bit with an envious worm,
Ere he can spread his sweet leaves to the air,
Or dedicate his beauty to the sun.
Could we but learn from whence his sorrows grow.
We would as willingly give cure as know.
""")

Sentence length: 187 words
> 184 recognized words: ['verona', 'misadventured', 'true']

[13229,
 54272,
 28978,
 62964,
 22419,
 42456,
 22419,
 24673,
 12348,
 12641,
 21653,
 19407,
 16373,
 23830,
 30420,
 23221,
 29105,
 13884,
 19806,
 19995,
 12348,
 27956,
 29245,
 20989,
 27956,
 23000,
 60384,
 23830,
 24104,
 14035,
 41844,
 21157,
 19455,
 14058,
 13229,
 24390,
 30822,
 19243,
 19455,
 14905,
 'cross',
 40400,
 14138,
 14042,
 21375,
 12427,
 39250,
 58603,
 25869,
 12525,
 14042,
 26363,
 28460,
 14042,
 'parents',
 14718,
 14035,
 41860,
 39397,
 19455,
 14042,
 26363,
 'mark',
 21224,
 30423,
 14035,
 43069,
 19455,
 14042,
 'parents',
 17573,
 12356,
 28480,
 14042,
 27797,
 25131,
 19639,
 27083,
 60807,
 21958,
 19652,
 14035,
 13229,
 'hours',
 13625,
 19455,
 19407,
 14842,
 14035,
 12356,
 22547,
 12313,
 12525,
 19076,
 25498,
 30139,
 12730,
 22864,
 15944,
 20387,
 19407,
 13903,
 15944,
 14732,
 13884,
 20517,
 28978,
 28510,
 53847,
 30423,
 20642,
 19396,
 24228,
 28480,
 23124,
 22955,
 19187,
 'affections',
 42992,
 21958,
 13884,
 54346,
 22517,
 12460,
 19623,
 16748,
 22740,
 28480,
 13884,
 54346,
 15292,
 16171,
 30423,
 15292,
 27652,
 15292,
 24716,
 23830,
 15419,
 30423,
 42497,
 30015,
 21958,
 14035,
 28797,
 29136,
 12525,
 30396,
 42102,
 12152,
 24976,
 23124,
 28638,
 15191,
 22955,
 14411,
 21703,
 13884,
 14035,
 30552,
 19566,
 26421,
 22955,
 29747,
 13884,
 14035,
 14578,
 27083,
 12641,
 28480,
 21685,
 23830,
 12346,
 22955,
 15405,
 23213,
 12641,
 12168,
 30015,
 36597,
 23722,
 26566,
 30015,
 21942]